# Generated by Django 4.2.24 on 2025-10-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_rented', models.BooleanField(default=False, verbose_name='Rented')),
                ('is_damaged', models.BooleanField(default=False, verbose_name='Damaged')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='In Maintenance')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Vehicle Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
