# Generated by Django 4.2.24 on 2025-10-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Rate (USD)'),
        ),
    ]
