# Generated by Django 4.2.24 on 2025-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_daily_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_active',
        ),
        migrations.AddField(
            model_name='car',
            name='in_fleet',
            field=models.BooleanField(default=True, verbose_name='In Fleet'),
        ),
    ]
