# Generated by Django 4.2.24 on 2026-01-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_is_active_to_in_fleet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='daily_price',
            new_name='daily_rate',
        ),
    ]
